- .gitignore
- PULL_REQUEST_TEMPLATE.md
- package-lock.json
- package.json
- src/actions/index.js
- src/components/App/App.js
- src/components/App/App.test.js
- src/reducers/userReducer.js
- src/setupTests.js
- [] Bug Fix
- [] Refactor
* description - added in test setup file and basic files for making fetches. Finished Redux loop.
* Closes #
> Basic test setup

- src/components/App/App.js
- src/utilities/apiCalls/apiCalls.js
- src/utilities/helpers/helpers.js
- [] Bug Fix
- [] Refactor
* description - setup post method to the backend to handle user
* Closes #15 
> Handle user to be

- src/components/App/App.js
- src/components/Event/Event.css
- src/components/Event/Event.js
- src/components/Event/Event.scss
- src/components/Map/Map.js
- src/utilities/apiCalls/apiCalls.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
Rendering markers for events
* Closes #
> Mapbox markers

- package-lock.json
- package.json
- public/index.html
- src/components/EventModal/EventModal.js
- src/components/EventPopup/EventPopup.js
- src/components/Events/Events.js
- src/components/Map/Map.js
- src/utilities/apiCalls/apiCalls.js
- src/utilities/helpers/helpers.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> Event popup

- package-lock.json
- package.json
- public/index.html
- src/components/App/App.js
- src/components/EventModal/EventModal.js
- src/components/EventPopup/EventPopup.js
- src/components/Events/Events.js
- src/components/Map/Map.js
- src/utilities/apiCalls/apiCalls.js
- src/utilities/helpers/helpers.js
- [] Reviewed
- [] Bug Fix
* description
- Refactored helpers file, implemented client-side favorite handling
* Closes #
> Refactor 1

- src/components/EventModal/EventModal.css
- src/components/EventModal/EventModal.js
- src/components/EventModal/EventModal.scss
- src/components/Events/Events.js
- src/components/Map/Map.js
- src/containers/App/App.test.js
- src/containers/App/__snapshots__/App.test.js.snap
- src/data/mockUser.js
- src/utilities/apiCalls/apiCalls.js
- src/utilities/helpers/helpers.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
- Successfully Posts favorites to Backend
> Favorites 1

- src/containers/App/__snapshots__/App.test.js.snap
- [] Refactor
-Resolve nav-bar and routes/ combine tests
> resolve tests conflict

- src/actions/index.js
- src/components/EventModal/EventModal.js
- src/reducers/eventsReducer.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
setting watchlist in store
> Event store

- src/actions/index.js
- src/components/Events/Events.js
- src/reducers/eventsReducer.js
- src/reducers/watchListReducer.js
- src/utilities/apiCalls/apiCalls.js
- [] Reviewed
- [] Refactor
Resolve watchlist toggle to persist on modal close
> Watchlist store

- src/components/Events/Events.js
- src/utilities/apiCalls/apiCalls.js
- [] Reviewed
- [] Bug Fix
* description
* Closes #
> Remove Clogs

- package.json
- src/actions/index.js
- src/components/Events/Events.js
- src/components/FilterBar/FilterBar.css
- src/components/FilterBar/FilterBar.js
- src/components/FilterBar/FilterBar.scss
- src/components/HomeDisplay/HomeDisplay.js
- src/components/Map/Map.js
- src/components/Map/__snapshots__/Map.test.js.snap
- src/containers/App/App.js
- src/containers/WatchList/WatchList.js
- src/data/mockEvents.js
- src/data/mockUserParams.js
- src/reducers/eventsReducer.js
- src/reducers/index.js
- src/reducers/tests/eventsReducer.test.js
- src/reducers/tests/userReducer.test.js
- src/reducers/tests/watchListReducer.test.js
- src/reducers/userReducer.js
- src/reducers/userReducer.test.js
- src/reducers/watchListReducer.js
- src/utilities/apiCalls/apiCalls.js
- src/utilities/apiCalls/apiCalls.test.js
- src/utilities/helpers/helpers.js
- src/utilities/helpers/helpers.test.js
- [] Reviewed
- [] Refactor
Implemented a search by city suggestion box
> Search filter implementation

- src/components/EventTab/EventTab.css
- src/components/EventTab/EventTab.js
- src/components/EventTab/EventTab.scss
- [] Reviewed
- [] Bug Fix
- [] Refactor
- Create EventTab component
> Add eventTab details

- src/components/EventTab/EventTab.css
- src/components/EventTab/EventTab.js
- src/components/EventTab/EventTab.scss
- src/components/Events/Events.js
- src/components/FilterBar/FilterBar.css
- src/components/FilterBar/FilterBar.scss
- src/index.css
- src/utilities/helpers/helpers.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
- Styling to Event tab and position to search bar
> Event tab 2

- .env.development
- src/components/EventTab/__snapshots__/EventTab.test.js.snap
- src/components/Events/__snapshots__/Events.test.js.snap
- src/components/Profile/Profile.js
- src/components/Profile/Profile.test.js
- src/components/Profile/__snapshots__/Profile.test.js.snap
- src/components/UserLocation/UserLocation.test.js
- src/components/UserLocation/__snapshots__/UserLocation.test.js.snap
- src/utilities/apiCalls/apiCalls.js
- src/utilities/helpers/helpers.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> Add snap-shot test

- .gitignore
- src/components/LoginDisplay/LoginDisplay.js
- src/components/Map/Map.js
- src/utilities/apiCalls/apiCalls.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> Create .env.development file

- src/components/SelectedInfoContainer/SelectedInfoContainer.js
- src/utilities/apiCalls/apiCalls.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> added in alts

- src/containers/App/App.css
- src/containers/App/App.js
- src/containers/App/App.scss
- src/containers/NavBar/NavBar.css
- src/containers/NavBar/NavBar.scss
- src/utilities/apiCalls/apiKeys.js
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> CSS Styling

- src/containers/App/App.css
- src/containers/App/App.scss
- src/containers/NavBar/NavBar.css
- src/containers/NavBar/NavBar.scss
- src/containers/WatchList/WatchList.css
- src/containers/WatchList/WatchList.scss
- [] Bug Fix
- [] Refactor
Styling on navbar and events tab
> Style navbar; position close button, create quarter circle

- src/components/LoginDisplay/LoginDisplay.css
- src/components/LoginDisplay/LoginDisplay.js
- src/components/LoginDisplay/LoginDisplay.scss
- src/components/Routes/Routes.js
- src/containers/App/App.css
- src/containers/App/App.js
- src/containers/App/App.scss
- src/index.css
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> Login style

- src/components/EventModal/EventModal.css
- src/components/EventModal/EventModal.scss
- src/containers/App/App.css
- src/containers/App/App.js
- src/containers/App/App.scss
- src/containers/EventTab/EventTab.css
- src/containers/EventTab/EventTab.scss
- [] Reviewed
- [] Bug Fix
- [] Refactor
Responsive design on modal and tab
> Implement responsive design on modal and tabs

- src/components/LoginDisplay/LoginDisplay.css
- src/components/LoginDisplay/LoginDisplay.scss
- src/containers/App/App.js
- src/containers/EventTab/EventTab.css
- src/containers/EventTab/EventTab.scss
- src/containers/NavBar/NavBar.css
- src/containers/NavBar/NavBar.scss
- src/containers/Profile/Profile.css
- src/containers/Profile/Profile.scss
- src/containers/WatchList/WatchList.css
- src/containers/WatchList/WatchList.scss
- [] Reviewed
- [] Bug Fix
- [] Refactor
* description
* Closes #
> Login styling

- src/components/SelectedInfoContainer/SelectedInfoContainer.css
- src/components/SelectedInfoContainer/SelectedInfoContainer.js
- src/components/SelectedInfoContainer/SelectedInfoContainer.scss
- src/components/WatchListCard/WatchListCard.css
- src/components/WatchListCard/WatchListCard.scss
- src/containers/WatchList/WatchList.css
- src/containers/WatchList/WatchList.scss
- [] Bug Fix
- [] Refactor
* description
* Closes #
> Style WatchList
